/**
 * Business logic calculations for KoinX Tax Loss Harvesting
 */

export const STCG_TAX_RATE = 0.30; // 30%
export const LTCG_TAX_RATE = 0.20; // 20%

/**
 * Calculates pre-harvest capital gains metrics
 * @param {Object} capitalGains - Capital gains from API { stcg: { profits, losses }, ltcg: { profits, losses } }
 */
export const calculatePreHarvest = (capitalGains) => {
  if (!capitalGains) return null;

  const { stcg, ltcg } = capitalGains;

  const netStcg = stcg.profits - stcg.losses;
  const netLtcg = ltcg.profits - ltcg.losses;
  const realised = netStcg + netLtcg;

  return {
    stcg: {
      profits: stcg.profits,
      losses: stcg.losses,
      net: netStcg
    },
    ltcg: {
      profits: ltcg.profits,
      losses: ltcg.losses,
      net: netLtcg
    },
    realised
  };
};

/**
 * Calculates post-harvest capital gains metrics based on selected holdings
 * @param {Object} capitalGains - Base capital gains from API
 * @param {Array} selectedHoldings - Array of selected holdings
 */
export const calculatePostHarvest = (capitalGains, selectedHoldings) => {
  if (!capitalGains) return null;

  // Clone starting values
  let stcgProfits = capitalGains.stcg.profits;
  let stcgLosses = capitalGains.stcg.losses;
  let ltcgProfits = capitalGains.ltcg.profits;
  let ltcgLosses = capitalGains.ltcg.losses;

  let stcgHarvestedLoss = 0;
  let ltcgHarvestedLoss = 0;

  // Apply selected holdings to After Harvesting values
  selectedHoldings.forEach((holding) => {
    // STCG
    if (holding.stcg && holding.stcg.gain !== undefined) {
      if (holding.stcg.gain > 0) {
        stcgProfits += holding.stcg.gain;
      } else if (holding.stcg.gain < 0) {
        stcgLosses += Math.abs(holding.stcg.gain);
        stcgHarvestedLoss += Math.abs(holding.stcg.gain);
      }
    }

    // LTCG
    if (holding.ltcg && holding.ltcg.gain !== undefined) {
      if (holding.ltcg.gain > 0) {
        ltcgProfits += holding.ltcg.gain;
      } else if (holding.ltcg.gain < 0) {
        ltcgLosses += Math.abs(holding.ltcg.gain);
        ltcgHarvestedLoss += Math.abs(holding.ltcg.gain);
      }
    }
  });

  const netStcg = stcgProfits - stcgLosses;
  const netLtcg = ltcgProfits - ltcgLosses;
  const realised = netStcg + netLtcg;

  // Calculate tax savings
  // Tax savings are the tax offsets generated by harvesting losses
  const taxSavings = (stcgHarvestedLoss * STCG_TAX_RATE) + (ltcgHarvestedLoss * LTCG_TAX_RATE);

  return {
    stcg: {
      profits: stcgProfits,
      losses: stcgLosses,
      net: netStcg
    },
    ltcg: {
      profits: ltcgProfits,
      losses: ltcgLosses,
      net: netLtcg
    },
    realised,
    taxSavings
  };
};

/**
 * Formats a number as currency (defaults to INR ₹, supports USD $)
 * @param {number} value
 * @param {string} currency - 'INR' or 'USD'
 */
export const formatCurrency = (value, currency = "INR") => {
  const symbol = currency === "USD" ? "$" : "₹";
  
  // Format with thousand separators and 2 decimal places
  const formatted = Math.abs(value).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

  return `${value < 0 ? "-" : ""}${symbol}${formatted}`;
};
